import os
import hashlib
from flask import Flask, render_template_string, request, redirect, url_for
from cryptography.fernet import Fernet
from base64 import urlsafe_b64encode

app = Flask(__name__)

# --- 1. KEY MANAGEMENT (CRITICAL STEP) ---
# NOTE: In a real application, you would load this key from a secure environment variable
# or a secrets manager, not hardcode it.
# We generate a consistent, static key for demonstration purposes.

# Utility function to generate a key (Run this once to get a key)
def generate_fernet_key():
    return urlsafe_b64encode(os.urandom(32))

# Use a pre-generated key for consistency in the example
# The key below is a placeholder, you should generate your own once!
# Example key generated by generate_fernet_key()
STATIC_FERNET_KEY = b'QW2Y3-qY8x_pS-X2pC7U5FhS5J-KjM4yD7T4V3eK9aA='

# Initialize Fernet instance with the static key
cipher_suite = Fernet(STATIC_FERNET_KEY)

# --- 2. CRYPTOGRAPHIC LOGIC FUNCTIONS ---

def perform_hashing(data):
    """Performs SHA-256 hashing."""
    try:
        data_bytes = data.encode('utf-8')
        # Use the standard hashlib library for hashing
        hash_object = hashlib.sha256(data_bytes)
        return hash_object.hexdigest(), "SHA-256 Hash"
    except Exception as e:
        return f"Error: {e}", "Error"

def perform_encryption(data):
    """Encrypts data using Fernet (AES-128 standard)."""
    try:
        data_bytes = data.encode('utf-8')
        # Use the cryptography library for encryption
        encrypted_data = cipher_suite.encrypt(data_bytes)
        # The result is already base64 encoded and safe to display
        return encrypted_data.decode('utf-8'), "Fernet Ciphertext (AES)"
    except Exception as e:
        return f"Error: {e}", "Error"

def perform_decryption(data):
    """Decrypts data using Fernet."""
    try:
        data_bytes = data.encode('utf-8')
        # Use the cryptography library for decryption
        decrypted_data = cipher_suite.decrypt(data_bytes)
        return decrypted_data.decode('utf-8'), "Decrypted Plaintext"
    # Fernet decryption fails if the token is invalid, expired, or corrupted
    except Exception:
        return "Decryption Error: Invalid or corrupt token/ciphertext.", "Decryption Error"


# --- 3. FLASK ROUTES & WEB INTERFACE ---

@app.route('/', methods=['GET', 'POST'])
def index():
    result = None
    result_type = None
    input_text = ""

    if request.method == 'POST':
        input_text = request.form.get('input_text', '')
        operation = request.form.get('operation')

        if not input_text:
            result = "Please enter some text."
            result_type = "Warning"
        elif operation == 'hash':
            result, result_type = perform_hashing(input_text)
        elif operation == 'encrypt':
            result, result_type = perform_encryption(input_text)
        elif operation == 'decrypt':
            result, result_type = perform_decryption(input_text)
        
    return render_template_string(HTML_TEMPLATE, 
                                  result=result, 
                                  result_type=result_type,
                                  input_text=input_text)

# --- 4. ELEGANT HTML TEMPLATE ---

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Crypto/Hash Tool</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .result-box {
            background-color: #f8f9fa; 
            border: 1px solid #dee2e6;
            border-left: 5px solid #0d6efd; /* Blue stripe for results */
            padding: 15px;
            margin-top: 20px;
            word-break: break-all;
            white-space: pre-wrap;
            font-family: monospace;
        }
        .error-box {
            border-left-color: #dc3545 !important; /* Red stripe for errors */
        }
    </style>
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">🔐 Crypto & Hash Playground</h1>
        
        <form method="POST" action="/" class="mb-5">
            <div class="mb-3">
                <label for="input_text" class="form-label">Input Text or Ciphertext</label>
                <textarea class="form-control" id="input_text" name="input_text" rows="4" required>{{ input_text }}</textarea>
            </div>
            
            <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                <button type="submit" name="operation" value="hash" class="btn btn-dark btn-lg">Hash (SHA-256)</button>
                <button type="submit" name="operation" value="encrypt" class="btn btn-success btn-lg">Encrypt (Fernet/AES)</button>
                <button type="submit" name="operation" value="decrypt" class="btn btn-danger btn-lg">Decrypt (Fernet/AES)</button>
            </div>
        </form>

        {% if result %}
            <h2>✨ Result:</h2>
            <div class="result-box {% if 'Error' in result_type or 'Warning' in result_type %}error-box{% endif %}">
                <p class="text-muted small mb-1">{{ result_type }}</p>
                <p class="lead fw-bold">{{ result }}</p>
            </div>
        {% endif %}

        <footer class="mt-5 pt-3 border-top text-muted small">
            <p><strong>Note on Encryption:</strong> This tool uses a static Fernet key for demonstration. Fernet provides secure, authenticated symmetric encryption (based on AES).</p>
        </footer>
    </div>
</body>
</html>
"""

if __name__ == '__main__':
    # You can generate a new key if needed:
    # print("New Fernet Key:", generate_fernet_key())
    
    # Run the Flask app
    app.run(debug=True)